"""Casos de uso - Application logic."""

from .events import (
    CreateEventInput,
    UpdateEventPatch,
    add_event_note,
    create_event,
    cycle_event_repeat,
    delete_event,
    delete_event_note,
    list_events_for_date,
    toggle_event_notify,
    update_event,
    update_event_note,
)
from .tasks import (
    CreateTaskInput,
    UpdateTaskPatch,
    add_task_note,
    create_subtask,
    create_task,
    cycle_task_status,
    delete_task,
    delete_task_note,
    get_task_by_id,
    list_tasks,
    toggle_task_priority,
    update_task,
    update_task_note,
)

__all__ = [
    "CreateEventInput",
    "UpdateEventPatch",
    "add_event_note",
    "update_event_note",
    "delete_event_note",
    "create_event",
    "update_event",
    "delete_event",
    "list_events_for_date",
    "toggle_event_notify",
    "cycle_event_repeat",

    "CreateTaskInput",
    "UpdateTaskPatch",
    "create_task",
    "create_subtask",
    "update_task",
    "delete_task",
    "list_tasks",
    "toggle_task_priority",
    "cycle_task_status",
    "get_task_by_id",
    "add_task_note",
    "update_task_note",
    "delete_task_note",
]
